/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package flightreservationsystem;

import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;

/**
 *
 * @author Nim
 */
public class AddAirport extends javax.swing.JFrame {

    /**
     * Creates new form AddAirport
     */
    public AddAirport() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        airport_id_txt = new javax.swing.JTextField();
        city_txt = new javax.swing.JTextField();
        country_txt = new javax.swing.JTextField();
        airport_add_btn = new javax.swing.JButton();
        airport_clear_btn = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1368, 765));
        getContentPane().setLayout(null);

        jLabel2.setText("Airport Info");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(160, 100, 90, 16);

        jLabel3.setText("Airport ID");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(50, 150, 90, 16);

        jLabel4.setText("City");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(50, 190, 80, 16);

        jLabel5.setText("Country");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(50, 240, 90, 16);
        getContentPane().add(airport_id_txt);
        airport_id_txt.setBounds(200, 140, 220, 24);
        getContentPane().add(city_txt);
        city_txt.setBounds(200, 190, 220, 24);
        getContentPane().add(country_txt);
        country_txt.setBounds(200, 240, 220, 24);

        airport_add_btn.setText("Add");
        airport_add_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                airport_add_btnActionPerformed(evt);
            }
        });
        getContentPane().add(airport_add_btn);
        airport_add_btn.setBounds(200, 310, 90, 32);

        airport_clear_btn.setText("Clear");
        getContentPane().add(airport_clear_btn);
        airport_clear_btn.setBounds(320, 310, 100, 32);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/flightreservationsystem/home icon.jpg"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(40, 10, 50, 50);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/flightreservationsystem/back-icon.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(90, 10, 60, 50);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/flightreservationsystem/line_glare_light_color_background.jpg"))); // NOI18N
        getContentPane().add(jLabel6);
        jLabel6.setBounds(30, 80, 440, 370);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/flightreservationsystem/dark-cyan-color-wallpaper-3.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1220, 640);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void airport_add_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_airport_add_btnActionPerformed
        String airport_id = airport_id_txt.getText();
        String city = city_txt.getText();
        String country = country_txt.getText();

        try {
           // PrintWriter writer = new PrintWriter("input.txt", "UTF-8");
            PrintWriter writer= new PrintWriter(new FileWriter("input.txt", true));
            writer.println(airport_id+"("+city+","+country+")");
            
            writer.close();
        } catch (IOException e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_airport_add_btnActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Welcome welcom_obj1 = new Welcome();
        welcom_obj1.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Login login_obj2= new Login();
        login_obj2.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddAirport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddAirport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddAirport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddAirport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddAirport().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton airport_add_btn;
    private javax.swing.JButton airport_clear_btn;
    private javax.swing.JTextField airport_id_txt;
    private javax.swing.JTextField city_txt;
    private javax.swing.JTextField country_txt;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    // End of variables declaration//GEN-END:variables
}
