/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package flightreservationsystem;

import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.Calendar;
import java.util.GregorianCalendar;
import javax.swing.Timer;

/**
 *
 * @author Nim
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        try {

            this.setUndecorated(true);
            this.setAlwaysOnTop(false);
            this.setResizable(false);
            this.setVisible(true);

            initComponents();
            Toolkit tk = Toolkit.getDefaultToolkit();
            int xsize = (int) tk.getScreenSize().getWidth();
            int ysize = (int) tk.getScreenSize().getHeight();
            this.setSize(xsize, ysize);

            ActionListener taskPerformer = new ActionListener() {
                @Override
                public void actionPerformed(ActionEvent e) {
                    timeLabel.setText(CurrentTime());
                }

            };

            Timer t = new Timer(1000, taskPerformer);
            t.start();

            

        } catch (Exception e) {
        }
    }
    
     public String CurrentTime() {

        Calendar cal = new GregorianCalendar();
        int second = cal.get(Calendar.SECOND);
        int min = cal.get(Calendar.MINUTE);
        int hour = cal.get(Calendar.HOUR_OF_DAY);
        String s = (checkTime(hour) + ":" + checkTime(min) + ":" + checkTime(second));
        timeLabel.setText(s);
        return s;
    }

    public String checkTime(int t) {
        String time1;
        if (t < 10) {
            time1 = ("0" + t);
        } else {
            time1 = ("" + t);
        }
        return time1;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        title = new javax.swing.JLabel();
        timeLabel = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        loginbtn = new javax.swing.JButton();
        minimizebtn = new javax.swing.JButton();
        resetbtn = new javax.swing.JButton();
        registerlbl = new javax.swing.JLabel();
        closebtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1363, 765));
        setPreferredSize(new java.awt.Dimension(1363, 765));
        getContentPane().setLayout(null);

        title.setFont(new java.awt.Font("Nyala", 1, 24)); // NOI18N
        title.setForeground(new java.awt.Color(102, 0, 102));
        title.setText("Flight Reservation System");
        getContentPane().add(title);
        title.setBounds(320, 0, 265, 33);

        timeLabel.setFont(new java.awt.Font("Digital-7", 0, 22)); // NOI18N
        getContentPane().add(timeLabel);
        timeLabel.setBounds(1200, 0, 115, 30);

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("User ID");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(470, 300, 80, 16);

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Password");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(470, 340, 80, 21);

        jTextField1.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        getContentPane().add(jTextField1);
        jTextField1.setBounds(580, 300, 200, 29);

        jTextField2.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        getContentPane().add(jTextField2);
        jTextField2.setBounds(580, 340, 200, 29);

        loginbtn.setText("Login");
        getContentPane().add(loginbtn);
        loginbtn.setBounds(580, 400, 80, 32);

        minimizebtn.setIcon(new javax.swing.ImageIcon("D:\\JAPURA\\CS\\CS\\FistYear\\FinalAssignment\\FlightReservationSystem\\src\\flightreservationsystem\\minimize-window-xxl (Custom).png")); // NOI18N
        minimizebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                minimizebtnActionPerformed(evt);
            }
        });
        getContentPane().add(minimizebtn);
        minimizebtn.setBounds(1310, 0, 20, 20);

        resetbtn.setText("Reset");
        getContentPane().add(resetbtn);
        resetbtn.setBounds(697, 400, 80, 32);

        registerlbl.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        registerlbl.setForeground(new java.awt.Color(0, 0, 0));
        registerlbl.setText("Register");
        getContentPane().add(registerlbl);
        registerlbl.setBounds(470, 450, 90, 20);

        closebtn.setIcon(new javax.swing.ImageIcon("D:\\JAPURA\\CS\\CS\\FistYear\\FinalAssignment\\FlightReservationSystem\\src\\flightreservationsystem\\close-icon-16 (Custom).png")); // NOI18N
        closebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closebtnActionPerformed(evt);
            }
        });
        getContentPane().add(closebtn);
        closebtn.setBounds(1340, 0, 20, 20);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/flightreservationsystem/flight.jpg"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 1366, 765);
        jLabel2.getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void closebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closebtnActionPerformed
        this.dispose();
    }//GEN-LAST:event_closebtnActionPerformed

    private void minimizebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_minimizebtnActionPerformed
        this.setState(Login.ICONIFIED);
    }//GEN-LAST:event_minimizebtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton closebtn;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JButton loginbtn;
    private javax.swing.JButton minimizebtn;
    private javax.swing.JLabel registerlbl;
    private javax.swing.JButton resetbtn;
    private javax.swing.JLabel timeLabel;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
}
